import type { Metadata } from "next";
import { Barlow, Staatliches } from "next/font/google";
import "./globals.css";


const barlow = Barlow({
   weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-barlow",
});
const staatliches = Staatliches({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-staatliches"
})

export const metadata: Metadata = {
  title: "Repointing Brickwork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} ${staatliches.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
